# Based on CUDA 12.2.0 image
FROM nvidia/cuda:12.2.0-runtime-ubuntu22.04

# Update and install essential packages
RUN apt-get update && apt-get install -y \
    wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Anaconda
RUN wget https://repo.anaconda.com/archive/Anaconda3-2023.07-1-Linux-x86_64.sh -O ~/anaconda.sh \
    && bash ~/anaconda.sh -b -p /opt/conda \
    && rm ~/anaconda.sh

# Add Anaconda to environment variables
ENV PATH="/opt/conda/bin:${PATH}"

# Install Python 3.11 in the default environment
RUN conda install -y python=3.11

# Create working directory
WORKDIR /app

# Copy requirements.txt to the container
COPY requirements.txt .

# Install requirements.txt in the default environment
RUN /opt/conda/bin/pip install -r requirements.txt
RUN /opt/conda/bin/pip install opencv-python-headless

RUN /opt/conda/bin/pip install -U "jax[cuda12]"
RUN apt-get update && apt-get install -y cuda-compat-12-2

# Set default Python commands when running a container
CMD ["bash"]